ALTER TABLE user_profiles 
ADD COLUMN website_1 VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
ADD COLUMN website_2 VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
ADD COLUMN website_3 VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
ADD COLUMN aim VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
ADD COLUMN msn VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
ADD COLUMN gchat VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
ADD COLUMN facebook VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
ADD COLUMN lastfm VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
ADD COLUMN about_blurb text COLLATE utf8_bin,
ADD COLUMN flickr_username VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
ADD COLUMN delicious_username VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
ADD COLUMN rss_feed_1 VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
ADD COLUMN rss_feed_2 VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
ADD COLUMN rss_feed_3 VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
ADD COLUMN custom_css VARCHAR(255) COLLATE utf8_bin DEFAULT NULL;

ALTER TABLE users
ADD COLUMN `new_post_notification` tinyint(1) DEFAULT NULL,
ADD COLUMN `random_titles` tinyint(1) DEFAULT NULL,
ADD COLUMN  `timezone` varchar(255) COLLATE utf8_bin DEFAULT NULL;